version: '3'
services:
  mysql:
    image: mysql:latest
    ports:
    - 3306:3306
    container_name: mysql-player-docker
    network_mode: host
    environment:
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_DATABASE: playerDb
      MYSQL_USER: root123
      MYSQL_PASSWORD: root123
  favourite-service:
    image: favourite-service
    build: favouriteservice/
    restart: always
    network_mode: host
    container_name: favourite-service-container
    depends_on:
    - mysql
    ports:
    - 8081:8081
    expose:
    - 8081
  user-cric-service:
    image: user-cric-service
    build: userservice/
    restart: always
    container_name: user-cric-app-container
    network_mode: host
    depends_on:
    - mysql
    ports:
    - 8082:8082
    expose:
    - 8082
  angular:
    image: angular-front
    build: CPlayersUI/
    network_mode: host
    container_name: angular-docker1
    ports:
    - 4200:4200
  